
export const  getClientLegacyByDoc = async( prismaLegacyService: any,documento:string)=>await prismaLegacyService.$queryRaw<any[]>`
      SELECT 
        CAST(id AS UNSIGNED) as id,
        nombre,
        primer_nombre,
        segundo_nombre,
        primer_apellido,
        segundo_apellido,
        tipo_doc,
        num_doc,
        fecha_nacimiento,
        direccion,
        barrio,
        CAST(municipio_id AS UNSIGNED) as municipio_id,
        movil,
        fijo,
        email,
        placa,
        ocupacion,
        empresa,
        NULLIF(tipo_actividad, '') as tipo_actividad,
        CAST(codeudor_id AS UNSIGNED) as codeudor_id,
        numero_de_creditos,
        CAST(user_create_id AS UNSIGNED) as user_create_id,
        CAST(user_update_id AS UNSIGNED) as user_update_id,
        calificacion,
        created_at,
        updated_at,
        dir_empresa,
        tel_empresa,
        CAST(conyuge_id AS UNSIGNED) as conyuge_id,
        genero,
        NULLIF(estado_civil, '') as estado_civil,
        fecha_exp,
        lugar_exp,
        lugar_nacimiento,
        NULLIF(nivel_estudios, '') as nivel_estudios,
        antiguedad_movil,
        anos_residencia,
        NULLIF(envio_correspondencia, '') as envio_correspondencia,
        NULLIF(estrato, '') as estrato,
        meses_residencia,
        NULLIF(tipo_vivienda, '') as tipo_vivienda,
        nombre_arrendador,
        telefono_arrendador,
        cargo,
        descripcion_actividad,
        doc_empresa,
        fecha_vinculacion,
        NULLIF(tipo_contrato, '') as tipo_contrato,
        reportado
      FROM clientes
      WHERE num_doc = ${documento}
      LIMIT 1
      `;


    // await prismaLegacyService.$queryRaw<any[]>`
    //   SELECT 
    //     CAST(id AS UNSIGNED) as id,
    //     nombre,
    //     primer_nombre,
    //     segundo_nombre,
    //     primer_apellido,
    //     segundo_apellido,
    //     tipo_doc,
    //     num_doc,
    //     fecha_nacimiento,
    //     direccion,
    //     barrio,
    //     CAST(municipio_id AS UNSIGNED) as municipio_id,
    //     movil,
    //     fijo,
    //     email,
    //     placa,
    //     ocupacion,
    //     empresa,
    //     NULLIF(tipo_actividad, '') as tipo_actividad,
    //     CAST(codeudor_id AS UNSIGNED) as codeudor_id,
    //     numero_de_creditos,
    //     CAST(user_create_id AS UNSIGNED) as user_create_id,
    //     CAST(user_update_id AS UNSIGNED) as user_update_id,
    //     calificacion,
    //     created_at,
    //     updated_at,
    //     dir_empresa,
    //     tel_empresa,
    //     CAST(conyuge_id AS UNSIGNED) as conyuge_id,
    //     genero,
    //     NULLIF(estado_civil, '') as estado_civil,
    //     fecha_exp,
    //     lugar_exp,
    //     lugar_nacimiento,
    //     NULLIF(nivel_estudios, '') as nivel_estudios,
    //     antiguedad_movil,
    //     anos_residencia,
    //     NULLIF(envio_correspondencia, '') as envio_correspondencia,
    //     NULLIF(estrato, '') as estrato,
    //     meses_residencia,
    //     NULLIF(tipo_vivienda, '') as tipo_vivienda,
    //     nombre_arrendador,
    //     telefono_arrendador,
    //     cargo,
    //     descripcion_actividad,
    //     doc_empresa,
    //     fecha_vinculacion,
    //     NULLIF(tipo_contrato, '') as tipo_contrato,
    //     reportado
    //   FROM clientes
    //   WHERE num_doc = ${documento}
    //   LIMIT 1
    // `;